### ISSUE TITLE
Scanning bugs

### ISSUE THREAD

**Issue by jurajsomorovsky** [RUB-NDS/TLS-Scanner#16]
Checked with schokokeks.org

- RSA is set to true, even if no RSA cipher suite is offered
- prefers PFS is set to false
- Diverse RSA vulnerabilities (like Bleichenbacher) are set to unknown
- Heartbleed is set to unkknown
...

/cc @hannob

**Comment by ic0ns** [comment]
The Heartbleed test currently assumes that atleast one rsa ciphersuite is supported. With TLS-Attacker it is possible to reconfigure this - with the scanner not so easily. I'll fix this problem with the next TLS-Attacker release.

For the Bleichenbacher check there was a missing check if we are scanning for configuration problems or implementation problems. Therefore the Scanner reported Unknown and not false. 

The problems (all but the heartbleed one) are fixed in the v2.1 Branch. They will probably be merged into master by the end of the week. Thanks for reporting! Let me know if you experience further problems.

**Comment by ic0ns** [comment]
I fixed the mentioned problems. They are all solved with the release of TLS-Scanner 2.2
